export type ProjectLevel = 1 | 2 | 3

export interface ProjectStep {
  order: number
  title: string
  description: string
  duration: string
  tips?: string[]
}

export interface ResearchProject {
  id: string
  title: string
  description: string
  objectives: string[]
  level: ProjectLevel
  estimatedMinutes: number
  prerequisites: string[]
  steps: ProjectStep[]
  deliverables: string[]
  evaluationCriteria: string[]
  relatedCourseIds: string[]
  relatedKnowledgeIds: string[]
  relatedTaskIds: string[]
  phaseId?: string
}

export const researchProjects: ResearchProject[] = [
  // ── Level 1: Course Projects (30-60 min) ──
  {
    id: "CP-PY-001",
    title: "文件读取与基础清洗",
    description: "使用Python读取一个真实语料文件（TXT格式），完成编码检测、格式统一和基础清洗，输出清洗后的纯文本。",
    objectives: ["掌握Python文件读取的基本方法", "学会处理不同编码格式", "掌握基础文本清洗流程"],
    level: 1,
    estimatedMinutes: 45,
    prerequisites: ["kw-file", "kw-cleaning"],
    steps: [
      { order: 1, title: "准备文件", description: "找到一个TXT格式的语料文件（建议5000字以上），确认文件编码", duration: "5分钟" },
      { order: 2, title: "实现读取", description: "使用 open() 函数读取文件，处理可能的编码异常", duration: "10分钟", tips: ["使用 encoding 参数指定编码", "捕获 UnicodeDecodeError"] },
      { order: 3, title: "文本清洗", description: "去除多余空白、统一标点符号格式、去除空行", duration: "15分钟", tips: ["使用正则表达式 re.sub()", "strip() 去除首尾空白"] },
      { order: 4, title: "输出结果", description: "将清洗后的文本保存为新的TXT文件，打印前200字验证效果", duration: "10分钟" },
      { order: 5, title: "撰写笔记", description: "记录遇到的文件编码问题和清洗策略", duration: "5分钟" },
    ],
    deliverables: ["清洗后的txt文件", "清洗脚本.py", "处理笔记"],
    evaluationCriteria: ["正确处理编码问题", "清洗后无多余空白和空行", "脚本可复用"],
    relatedCourseIds: ["python-001", "python-002"],
    relatedKnowledgeIds: ["kw-file", "kw-cleaning"],
    relatedTaskIds: [],
  },
  {
    id: "CP-PY-002",
    title: "词频统计与可视化",
    description: "对清洗后的语料进行分词和词频统计，生成词频表并绘制词频分布图。",
    objectives: ["掌握中文分词工具的使用", "学会统计词频并输出表格", "掌握基础数据可视化"],
    level: 1,
    estimatedMinutes: 50,
    prerequisites: ["kw-token", "kw-frequency", "kw-visualization"],
    steps: [
      { order: 1, title: "分词处理", description: "使用 jieba 对语料进行分词，处理停用词", duration: "10分钟", tips: ["加载停用词表过滤", "使用 lcut() 方法"] },
      { order: 2, title: "词频统计", description: "统计每个词的出现次数，输出按频率降序排列的词频表", duration: "10分钟", tips: ["使用 collections.Counter", "输出前50高频词"] },
      { order: 3, title: "CSV保存", description: "将词频表保存为CSV格式，包含'词语'和'频次'两列", duration: "10分钟" },
      { order: 4, title: "可视化", description: "绘制前20高频词的柱状图，保存为图片", duration: "15分钟", tips: ["使用 matplotlib 或 pyecharts", "添加标题和轴标签"] },
      { order: 5, title: "分析记录", description: "简要分析高频词的特征和分布规律", duration: "5分钟" },
    ],
    deliverables: ["词频表CSV", "词频分布图", "分析笔记"],
    evaluationCriteria: ["分词效果合理", "词频统计准确", "可视化图表清晰"],
    relatedCourseIds: ["python-003", "python-004"],
    relatedKnowledgeIds: ["kw-token", "kw-frequency", "kw-visualization", "kw-csv"],
    relatedTaskIds: [],
  },
  {
    id: "CP-PY-003",
    title: "共现分析与搭配提取",
    description: "基于词频统计结果，选择目标词进行共现分析，提取词语搭配模式。",
    objectives: ["理解共现分析的基本原理", "实现滑动窗口共现统计", "提取并分析词语搭配"],
    level: 1,
    estimatedMinutes: 55,
    prerequisites: ["kw-frequency", "kw-cooccurrence"],
    steps: [
      { order: 1, title: "选择目标词", description: "从词频表中选择3-5个高频实词作为目标词", duration: "5分钟" },
      { order: 2, title: "实现共现统计", description: "设定滑动窗口大小（如±5），统计目标词共现词对", duration: "20分钟", tips: ["注意窗口边界处理", "考虑使用defaultdict计数"] },
      { order: 3, title: "计算关联强度", description: "计算互信息（PMI）或卡方值，筛选强关联搭配", duration: "15分钟" },
      { order: 4, title: "结果分析", description: "整理共现结果，分析目标词的典型搭配模式", duration: "10分钟" },
      { order: 5, title: "输出报告", description: "将结果整理为简短的分析报告", duration: "5分钟" },
    ],
    deliverables: ["共现矩阵CSV", "搭配分析报告"],
    evaluationCriteria: ["共现统计逻辑正确", "PMI计算正确", "分析有语言学意义"],
    relatedCourseIds: ["python-005"],
    relatedKnowledgeIds: ["kw-cooccurrence", "kw-frequency"],
    relatedTaskIds: [],
  },
  {
    id: "CP-CLI-001",
    title: "中文分词工具对比实验",
    description: "使用至少两种分词工具对同一语料进行分词，比较分词效果差异。",
    objectives: ["熟悉多种中文分词工具", "学会评估分词质量", "理解分词对后续任务的影响"],
    level: 1,
    estimatedMinutes: 50,
    prerequisites: ["kw-segmentation"],
    steps: [
      { order: 1, title: "准备测试语料", description: "收集100-200句中文测试语料，包含不同文体", duration: "10分钟" },
      { order: 2, title: "运行分词工具", description: "分别使用jieba、pkuseg、LAC等工具对同一语料分词", duration: "15分钟", tips: ["记录各工具的分词速度", "注意各工具的参数设置"] },
      { order: 3, title: "人工评估", description: "随机抽取50句人工判断分词正确率，记录错误类型", duration: "15分钟" },
      { order: 4, title: "撰写对比报告", description: "从准确率、速度、领域适应性等维度比较各工具", duration: "10分钟" },
    ],
    deliverables: ["分词结果对比表", "分词工具评测报告"],
    evaluationCriteria: ["评估方法科学", "数据量化充分", "结论有参考价值"],
    relatedCourseIds: ["edunlp-001"],
    relatedKnowledgeIds: ["kw-segmentation"],
    relatedTaskIds: [],
  },
  {
    id: "CP-LLM-001",
    title: "Prompt工程基础实验",
    description: "设计不同风格的Prompt，比较Zero-shot、Few-shot和Chain-of-Thought对LLM输出的影响。",
    objectives: ["掌握Prompt设计的基本原则", "理解不同Prompt策略的效果差异", "学会系统化评估Prompt质量"],
    level: 1,
    estimatedMinutes: 45,
    prerequisites: [],
    steps: [
      { order: 1, title: "设计测试任务", description: "选择2-3个语言学分析任务（如文本分类、偏误判断）", duration: "10分钟" },
      { order: 2, title: "编写Prompt", description: "对每个任务分别编写Zero-shot、Few-shot和CoT三种Prompt", duration: "15分钟", tips: ["Few-shot示例要典型", "CoT要展示推理步骤"] },
      { order: 3, title: "运行对比", description: "使用同一LLM对同一输入运行不同Prompt，记录输出", duration: "10分钟" },
      { order: 4, title: "效果分析", description: "比较不同Prompt策略的准确率和输出质量，总结最佳实践", duration: "10分钟" },
    ],
    deliverables: ["Prompt实验记录", "对比分析报告"],
    evaluationCriteria: ["实验设计完整", "对比维度合理", "结论有实践指导意义"],
    relatedCourseIds: ["llm-003", "llm-004"],
    relatedKnowledgeIds: [],
    relatedTaskIds: [],
  },

  // ── Level 2: Phase Projects (3-10 hours) ──

  // Phase 1
  {
    id: "P1-001",
    title: "分析100篇学习者作文",
    description: "对一个留学生作文语料库进行系统性分析，统计高频词、词类分布和其他语言特征。",
    objectives: ["掌握大规模文本处理流程", "学会从语料中提取语言学特征", "能够撰写数据分析报告"],
    level: 2,
    estimatedMinutes: 360,
    prerequisites: ["kw-frequency", "kw-corpus", "kw-csv"],
    steps: [
      { order: 1, title: "语料准备", description: "收集或获取100篇留学生作文（建议使用HSK动态作文语料库）", duration: "30分钟" },
      { order: 2, title: "数据预处理", description: "统一格式、清洗噪声、分段存储", duration: "45分钟", tips: ["注意保留元数据（水平等级、题目）", "使用DataFrame管理元数据"] },
      { order: 3, title: "分词与词性标注", description: "对全部作文进行分词和词性标注", duration: "45分钟" },
      { order: 4, title: "高频词统计", description: "统计总体词频、按水平等级分组统计频率", duration: "30分钟", tips: ["对比不同水平等级的词频差异", "关注虚词使用特征"] },
      { order: 5, title: "词汇丰富度分析", description: "计算类符/形符比（TTR）、词汇密度等指标", duration: "30分钟" },
      { order: 6, title: "结果可视化", description: "生成词云、高频词分布图、等级对比图", duration: "45分钟" },
      { order: 7, title: "撰写统计报告", description: "整理分析结果，撰写包含图表和数据分析的统计报告", duration: "45分钟", tips: ["报告结构：引言-方法-结果-讨论", "每个图表附简要说明"] },
    ],
    deliverables: ["词频表CSV", "统计分析报告（1000字以上）", "可视化图表集"],
    evaluationCriteria: ["数据处理流程完整", "分析方法科学合理", "报告结构清晰、论证充分"],
    relatedCourseIds: ["python-001", "python-002", "python-003", "python-004"],
    relatedKnowledgeIds: ["kw-file", "kw-corpus", "kw-token", "kw-frequency", "kw-visualization", "kw-csv"],
    relatedTaskIds: ["task-hsk", "task-essay", "task-visual", "task-large"],
    phaseId: "python",
  },
  {
    id: "P1-002",
    title: "构建教材词频分析器",
    description: "开发一个可复用的教材词频分析工具，能够对HSK标准教材进行词汇分析。",
    objectives: ["掌握教材文本的自动化处理方法", "构建可复用的词频分析工具", "输出可供教学参考的词频数据"],
    level: 2,
    estimatedMinutes: 300,
    prerequisites: ["kw-automation", "kw-csv", "kw-frequency"],
    steps: [
      { order: 1, title: "需求分析", description: "明确教材词频分析器的功能需求和输出格式", duration: "30分钟" },
      { order: 2, title: "教材文本数字化", description: "将HSK教材文本数字化，按课文分文件存储", duration: "60分钟", tips: ["OCR扫描教材需人工校对", "建议先处理1-2册"] },
      { order: 3, title: "编写分析脚本", description: "开发词频分析Python脚本，支持按课/按册统计", duration: "90分钟", tips: ["设计为函数式接口", "支持输出CSV和JSON格式"] },
      { order: 4, title: "运行分析", description: "对1-2册HSK教材进行词频分析，生成词频表", duration: "45分钟" },
      { order: 5, title: "结果验证", description: "对比分析结果与HSK词汇大纲，验证覆盖率", duration: "45分钟", tips: ["检查是否覆盖本册目标词汇", "分析超纲词情况"] },
      { order: 6, title: "工具封装", description: "将脚本封装为命令行工具或简单GUI", duration: "30分钟" },
    ],
    deliverables: ["词频分析Python脚本", "教材词频表（CSV）", "覆盖率验证报告"],
    evaluationCriteria: ["脚本可复用、代码规范", "分析结果准确可靠", "覆盖率验证方法科学"],
    relatedCourseIds: ["python-006", "python-007", "python-008", "python-009", "python-010"],
    relatedKnowledgeIds: ["kw-automation", "kw-csv", "kw-frequency", "kw-corpus"],
    relatedTaskIds: ["task-hsk", "task-textbook", "task-visual"],
    phaseId: "python",
  },

  // Phase 2
  {
    id: "P2-001",
    title: "教材词汇分析",
    description: "选择两套国际中文教育教材，从词汇覆盖、复现率、难度梯度等维度进行对比分析。",
    objectives: ["掌握教材对比分析的研究方法", "学会从多维度评估教材词汇编排", "能够撰写对比分析报告"],
    level: 2,
    estimatedMinutes: 420,
    prerequisites: ["kw-frequency", "kw-corpus", "kw-visualization"],
    steps: [
      { order: 1, title: "教材选择与数字化", description: "选择两套教材（如HSK标准教程 vs 博雅汉语），完成数字化", duration: "60分钟" },
      { order: 2, title: "分词与词表构建", description: "对两套教材全部分词，构建各自的词表", duration: "60分钟", tips: ["注意教材的等级划分", "保留课序信息"] },
      { order: 3, title: "词汇覆盖分析", description: "对比两套教材的词汇覆盖范围，与HSK词汇大纲交叉比对", duration: "60分钟" },
      { order: 4, title: "复现率分析", description: "统计核心词汇在教材中的复现频率和分布", duration: "60分钟", tips: ["关注新词的初次出现到复习的间隔", "计算复现间隔分布"] },
      { order: 5, title: "难度梯度分析", description: "分析各册之间的词汇难度过渡是否平滑", duration: "60分钟" },
      { order: 6, title: "撰写分析报告", description: "综合对比结果，撰写教材词汇分析报告", duration: "60分钟" },
    ],
    deliverables: ["对比分析数据集（CSV）", "教材词汇分析报告"],
    evaluationCriteria: ["分析方法多维度", "数据可视化充分", "结论有教学参考价值"],
    relatedCourseIds: ["edunlp-002", "edunlp-005", "edunlp-008"],
    relatedKnowledgeIds: ["kw-corpus", "kw-frequency", "kw-visualization", "kw-automation"],
    relatedTaskIds: ["task-hsk", "task-textbook"],
    phaseId: "cli",
  },
  {
    id: "P2-002",
    title: "学习者偏误分析",
    description: "基于学习者语料库，建立偏误分类体系，统计各类偏误的分布特征。",
    objectives: ["掌握偏误分析的基本方法论", "能够建立科学实用的偏误分类体系", "学会统计和分析偏误分布规律"],
    level: 2,
    estimatedMinutes: 400,
    prerequisites: ["kw-error-detection", "kw-pos-tagging", "kw-text-classification"],
    steps: [
      { order: 1, title: "文献综述", description: "阅读偏误分析相关文献，了解已有分类体系", duration: "45分钟" },
      { order: 2, title: "分类体系设计", description: "根据研究需求设计偏误分类体系（词汇/语法/语篇层面）", duration: "45分钟", tips: ["参考Corder的偏误分类框架", "分类要有互斥性和穷尽性"] },
      { order: 3, title: "语料标注", description: "对100篇学习者作文进行偏误标注", duration: "90分钟", tips: ["设计标注规范文档", "双人标注以计算一致性"] },
      { order: 4, title: "偏误统计", description: "按类型、频率、学习水平等维度统计偏误分布", duration: "60分钟" },
      { order: 5, title: "模式分析", description: "分析不同类型偏误的共现模式和成因", duration: "60分钟" },
      { order: 6, title: "撰写偏误报告", description: "撰寫偏误分析统计报告", duration: "60分钟" },
    ],
    deliverables: ["偏误分类体系文档", "标注数据集", "偏误统计分析报告"],
    evaluationCriteria: ["分类体系科学完整", "标注一致性达标", "统计分析维度丰富"],
    relatedCourseIds: ["edunlp-006", "edunlp-007"],
    relatedKnowledgeIds: ["kw-error-detection", "kw-pos-tagging", "kw-text-classification"],
    relatedTaskIds: ["task-essay", "task-error-auto"],
    phaseId: "cli",
  },
  {
    id: "P2-003",
    title: "HSK文本分级实验",
    description: "选取不同等级的HSK阅读文本，分析各级别的语言特征差异，建立可量化的分级指标。",
    objectives: ["理解文本可读性分析的核心指标", "掌握基于特征的分级方法", "能够提出可操作的分级建议"],
    level: 2,
    estimatedMinutes: 360,
    prerequisites: ["kw-text-classification", "kw-frequency", "kw-segmentation"],
    steps: [
      { order: 1, title: "语料收集", description: "收集HSK1-6级阅读文本各10篇以上", duration: "30分钟", tips: ["确保文本来源可靠", "记录每篇文本的官方级别"] },
      { order: 2, title: "特征提取", description: "提取每篇文本的词汇、句法、篇章层面的特征", duration: "60分钟", tips: ["词汇：TTR、词汇难度分布", "句法：平均句长、从句比例"] },
      { order: 3, title: "特征分析", description: "分析各特征与HSK等级的相关性，筛选有效分级特征", duration: "60分钟" },
      { order: 4, title: "分级模型构建", description: "基于筛选的特征构建文本分级模型（如逻辑回归或决策树）", duration: "60分钟" },
      { order: 5, title: "模型验证", description: "使用测试集验证分级模型的准确率", duration: "45分钟" },
      { order: 6, title: "撰写研究报告", description: "整理实验过程和结果，撰写研究报告", duration: "45分钟" },
    ],
    deliverables: ["特征数据集", "分级模型", "研究报告"],
    evaluationCriteria: ["特征选择有理论依据", "模型验证方法严谨", "结果有实践参考价值"],
    relatedCourseIds: ["edunlp-003", "edunlp-009", "edunlp-010"],
    relatedKnowledgeIds: ["kw-text-classification", "kw-frequency", "kw-segmentation"],
    relatedTaskIds: ["task-hsk", "task-textbook"],
    phaseId: "cli",
  },

  // Phase 3
  {
    id: "P3-001",
    title: "HSK阅读材料生成实验",
    description: "使用LLM生成不同等级的HSK阅读材料，比较不同Prompt策略对生成质量的影响。",
    objectives: ["掌握使用LLM生成教学材料的方法", "学会系统化评估生成内容质量", "优化Prompt策略以提高生成效果"],
    level: 2,
    estimatedMinutes: 360,
    prerequisites: [],
    steps: [
      { order: 1, title: "实验设计", description: "设计对比实验，确定要测试的Prompt变量（等级控制/词汇约束/句型控制）", duration: "30分钟" },
      { order: 2, title: "基线Prompt编写", description: "编写基础Prompt，包含等级、主题、字数等基本要求", duration: "30分钟", tips: ["明确指定目标HSK等级", "提供示例文本"] },
      { order: 3, title: "多策略Prompt设计", description: "设计多种Prompt策略（词汇表约束、例句模板、逐步生成等）", duration: "45分钟" },
      { order: 4, title: "生成执行", description: "使用不同Prompt各生成5篇文本，记录生成参数和结果", duration: "45分钟" },
      { order: 5, title: "质量评估", description: "从可读性、词汇适切性、语法正确性等维度评估生成质量", duration: "60分钟", tips: ["可邀请母语者参与评估", "使用分级指标量化评估"] },
      { order: 6, title: "结果分析", description: "比较各策略的生成效果，总结最佳实践", duration: "45分钟" },
      { order: 7, title: "撰写实验记录", description: "整理实验过程和结果，撰写实验报告", duration: "45分钟" },
    ],
    deliverables: ["生成文本集", "质量评估数据", "实验报告"],
    evaluationCriteria: ["实验设计有对照", "评估方法科学", "结论对实践有指导意义"],
    relatedCourseIds: ["llm-005", "llm-006", "llm-007"],
    relatedKnowledgeIds: [],
    relatedTaskIds: ["task-llm-prompt-optimize", "task-llm-hsk-gen"],
    phaseId: "llm",
  },
  {
    id: "P3-002",
    title: "作文反馈系统评测",
    description: "设计一个基于LLM的作文反馈系统，系统化比较AI反馈与教师反馈的效果差异。",
    objectives: ["掌握LLM在作文评改中的应用方法", "能够设计科学的效果评估方案", "理解AI辅助反馈的优势与局限"],
    level: 2,
    estimatedMinutes: 420,
    prerequisites: [],
    steps: [
      { order: 1, title: "反馈系统设计", description: "设计基于LLM的作文反馈系统架构，确定反馈维度（语法/词汇/内容/结构）", duration: "45分钟" },
      { order: 2, title: "Prompt模板开发", description: "为每个反馈维度开发专门的Prompt模板", duration: "45分钟", tips: ["设定评价标准", "要求给出修改建议"] },
      { order: 3, title: "数据集准备", description: "收集10篇学习者作文，并获取教师反馈作为参照", duration: "30分钟" },
      { order: 4, title: "AI反馈生成", description: "使用LLM对作文生成反馈", duration: "30分钟" },
      { order: 5, title: "对比评估", description: "邀请评估者从准确性、可理解性、建设性等维度比较AI与教师反馈", duration: "90分钟", tips: ["设计评分量表", "采用盲评方式"] },
      { order: 6, title: "差异分析", description: "分析AI反馈和教师反馈的异同，总结优势和不足", duration: "60分钟" },
      { order: 7, title: "撰写评测报告", description: "整理评测结果，撰写完整的评测报告", duration: "60分钟" },
    ],
    deliverables: ["反馈系统Prompt模板集", "对比评估数据集", "评测报告"],
    evaluationCriteria: ["评估维度全面", "评估方法科学", "结论客观有洞察"],
    relatedCourseIds: ["llm-009", "llm-010", "llm-011"],
    relatedKnowledgeIds: [],
    relatedTaskIds: ["task-llm-prompt-optimize", "task-llm-essay-feedback"],
    phaseId: "llm",
  },
  {
    id: "P3-003",
    title: "受控文本生成研究",
    description: "探索通过词汇表约束和句型模板控制LLM输出的方法，测试词汇约束对生成质量的影响。",
    objectives: ["掌握受控文本生成的核心技术", "理解词汇约束对生成质量的影响", "能够设计实用的受控生成方案"],
    level: 2,
    estimatedMinutes: 380,
    prerequisites: [],
    steps: [
      { order: 1, title: "研究设计", description: "确定要测试的词汇约束类型（限定词表/指定句型/控制字数等）", duration: "30分钟" },
      { order: 2, title: "约束方案实现", description: "实现多种词汇约束方案（Prompt约束 + 后处理过滤）", duration: "60分钟", tips: ["Prompt约束：在Prompt中指定可用词汇", "后处理：生成后替换/过滤词汇"] },
      { order: 3, title: "生成实验", description: "对不同难度级别分别进行受控生成实验", duration: "60分钟" },
      { order: 4, title: "质量控制评估", description: "评估生成文本的词汇符合率、语法正确性和自然度", duration: "60分钟", tips: ["词汇符合率：是否严格使用指定词汇", "自然度：请母语者进行5分制评分"] },
      { order: 5, title: "结果分析", description: "分析不同约束方法在词汇符合率和自然度之间的权衡", duration: "45分钟" },
      { order: 6, title: "撰写实验报告", description: "整理研究结果，撰写实验报告", duration: "45分钟" },
    ],
    deliverables: ["受控生成文本集", "约束方法对比数据", "实验报告"],
    evaluationCriteria: ["实验变量控制严格", "评估指标合理", "结论有实践价值"],
    relatedCourseIds: ["llm-012", "llm-013", "llm-014"],
    relatedKnowledgeIds: [],
    relatedTaskIds: ["task-llm-prompt-optimize", "task-llm-assessment", "task-llm-error-detection"],
    phaseId: "llm",
  },

  // ── Level 3: Capstone Project (20-50 hours) ──
  {
    id: "CAPSTONE-001",
    title: "AI辅助国际中文教育研究平台设计",
    description: "综合运用Python编程、NLP技术和LLM，设计并实现一个完整的AI辅助国际中文教育研究方案。该毕业项目要求跨阶段整合所有核心技能，完成从需求分析到原型实现的完整研究流程。",
    objectives: [
      "综合运用四阶段所学知识和技能",
      "独立完成一个完整的研究项目设计",
      "形成可展示的研究成果或原型系统",
      "撰写规范的学术研究报告",
    ],
    level: 3,
    estimatedMinutes: 1800,
    prerequisites: [],
    steps: [
      { order: 1, title: "选题与需求分析", description: "选择一个国际中文教育中的真实问题（如自动作文评改、教材分析、个性化学习等），进行需求分析", duration: "120分钟", tips: ["建议选择自己有数据或资源的方向", "明确研究问题和创新点"] },
      { order: 2, title: "文献综述", description: "查阅相关文献，了解已有研究和方法", duration: "180分钟", tips: ["关注CNKI、ACL Anthology等来源", "整理至少10篇参考文献"] },
      { order: 3, title: "方案设计", description: "设计技术方案，确定技术栈（Python库/NLP模型/LLM API等）和系统架构", duration: "180分钟" },
      { order: 4, title: "数据准备", description: "收集、清洗、标注研究所需要的数据", duration: "300分钟", tips: ["注意数据的代表性和规模", "保护数据隐私"] },
      { order: 5, title: "原型开发", description: "实现核心功能原型，包括数据处理、NLP分析和LLM集成", duration: "480分钟" },
      { order: 6, title: "实验与评估", description: "设计实验验证方案效果，收集评估数据", duration: "240分钟" },
      { order: 7, title: "结果分析", description: "分析实验结果，讨论发现和局限", duration: "120分钟" },
      { order: 8, title: "撰写报告", description: "撰写研究报告，包括摘要、引言、方法、结果、讨论和结论", duration: "180分钟" },
    ],
    deliverables: [
      "研究方案文档",
      "核心代码与数据",
      "研究报告（3000字以上）",
      "演示文稿或系统演示视频",
    ],
    evaluationCriteria: [
      "研究问题明确、有实际意义",
      "技术方案合理、综合运用多阶段知识",
      "实验设计科学、评估方法严谨",
      "报告规范、论证充分",
      "成果具有创新性或实用价值",
    ],
    relatedCourseIds: ["python-001", "python-003", "python-005", "edunlp-001", "edunlp-006", "llm-003", "llm-005", "llm-010"],
    relatedKnowledgeIds: ["kw-file", "kw-frequency", "kw-visualization", "kw-segmentation", "kw-text-classification", "kw-error-detection"],
    relatedTaskIds: ["task-hsk", "task-essay", "task-llm-prompt-optimize", "task-llm-assessment"],
    phaseId: "capstone",
  },

  // ── Coverage Sprint: Phase 3 targeted projects ──

  // Level 1: Course Projects
  {
    id: "CP-LLM-002",
    title: "RAG教育知识库构建",
    description: "构建一个小型国际中文教育知识库，使用向量数据库存储教材文本，实现基于RAG的检索问答。",
    objectives: ["理解RAG架构的基本原理", "掌握向量数据库的基本操作", "实现简单的知识问答功能"],
    level: 1,
    estimatedMinutes: 55,
    prerequisites: ["kw-llm-embedding", "kw-llm-rag", "kw-llm-vector-db"],
    steps: [
      { order: 1, title: "知识库设计", description: "确定知识库范围（如HSK语法知识、常见偏误类型等），收集或编写10条以上知识点", duration: "10分钟" },
      { order: 2, title: "文本向量化", description: "使用Embedding API将知识点文本转化为向量", duration: "15分钟", tips: ["使用OpenAI Embedding或本地模型", "注意文本分块策略"] },
      { order: 3, title: "存入向量库", description: "将向量存入ChromaDB或FAISS等向量数据库", duration: "15分钟", tips: ["记录元数据（来源、类别等）", "注意索引构建"] },
      { order: 4, title: "实现检索问答", description: "编写查询函数，实现语义检索并调用LLM生成答案", duration: "10分钟", tips: ["设置相似度阈值", "展示检索到的知识源"] },
      { order: 5, title: "测试与优化", description: "测试多个查询案例，调整分块大小和检索参数", duration: "5分钟" },
    ],
    deliverables: ["RAG知识库代码", "检索问答Demo", "测试记录"],
    evaluationCriteria: ["检索准确率合理", "问答引用知识源正确", "代码结构清晰"],
    relatedCourseIds: ["llm-008", "llm-009"],
    relatedKnowledgeIds: ["kw-llm-rag", "kw-llm-vector-db", "kw-llm-embedding"],
    relatedTaskIds: ["task-llm-knowledge-base", "task-llm-qa-system"],
  },
  {
    id: "CP-LLM-003",
    title: "LLM指令设计与Few-shot优化",
    description: "系统化设计指令模板，比较不同Few-shot示例数量和质量对LLM教育任务输出的影响。",
    objectives: ["掌握Instruction设计的最佳实践", "理解Few-shot示例选择策略", "学会量化评估Prompt质量"],
    level: 1,
    estimatedMinutes: 50,
    prerequisites: ["kw-llm-prompt", "kw-llm-fewshot", "kw-llm-cot", "kw-llm-instruction"],
    steps: [
      { order: 1, title: "任务选择", description: "选择2个教育NLP任务（如文本分级、偏误分类）", duration: "5分钟" },
      { order: 2, title: "指令模板设计", description: "为每个任务设计结构化指令模板（角色-任务-要求-输出格式）", duration: "15分钟", tips: ["明确角色设定", "指输出格式（JSON/Markdown）"] },
      { order: 3, title: "Few-shot示例构建", description: "为每个任务准备0/1/3/5个示例的Few-shot版本", duration: "15分钟", tips: ["选择典型且多样的示例", "示例要覆盖边界情况"] },
      { order: 4, title: "效果对比", description: "运行对比实验，记录各版本的输出质量和准确率", duration: "10分钟" },
      { order: 5, title: "分析总结", description: "分析示例数量与质量的非线性关系，总结指令设计原则", duration: "5分钟" },
    ],
    deliverables: ["指令模板库", "Few-shot对比数据", "优化建议报告"],
    evaluationCriteria: ["指令结构完整清晰", "对比实验有控制变量", "结论有实践指导意义"],
    relatedCourseIds: ["llm-001", "llm-002", "llm-004", "llm-005"],
    relatedKnowledgeIds: ["kw-llm-prompt", "kw-llm-fewshot", "kw-llm-cot", "kw-llm-instruction", "kw-llm-token"],
    relatedTaskIds: ["task-llm-prompt-optimize"],
  },
  {
    id: "CP-CLI-002",
    title: "情感分析与课堂反馈挖掘",
    description: "收集课堂反馈文本，使用情感分析和关键词提取技术挖掘教学改进方向。",
    objectives: ["掌握情感分析的基本方法", "学会从非结构化反馈中提取关键信息", "能够产出教学改进建议"],
    level: 1,
    estimatedMinutes: 50,
    prerequisites: ["kw-sentiment-analysis", "kw-ner"],
    steps: [
      { order: 1, title: "数据收集", description: "收集20条以上的课堂反馈文本（可使用模拟数据）", duration: "10分钟" },
      { order: 2, title: "情感分析", description: "使用SnowNLP或Transformers对反馈进行情感极性分析", duration: "15分钟", tips: ["注意中文情感词典的选择", "可对比不同工具的准确率"] },
      { order: 3, title: "关键词提取", description: "使用TF-IDF或TextRank提取反馈中的高频主题词", duration: "10分钟" },
      { order: 4, title: "可视化", description: "绘制情感分布图和词云，直观呈现反馈主题", duration: "10分钟" },
      { order: 5, title: "撰写反馈报告", description: "整理分析结果，提出教学改进建议", duration: "5分钟" },
    ],
    deliverables: ["情感分析结果", "反馈主题可视化", "教学改进建议"],
    evaluationCriteria: ["情感分析准确", "主题提取有意义", "建议具体可行"],
    relatedCourseIds: ["edunlp-012", "edunlp-013"],
    relatedKnowledgeIds: ["kw-sentiment-analysis", "kw-ner"],
    relatedTaskIds: ["task-feedback", "task-behavior"],
  },
  {
    id: "CP-CLI-003",
    title: "依存句法分析与学习者语言特征",
    description: "使用依存句法分析工具处理学习者文本，提取句法复杂度特征。",
    objectives: ["掌握依存句法分析的基本工具", "理解句法复杂度指标", "能够分析学习者的句法发展特征"],
    level: 1,
    estimatedMinutes: 55,
    prerequisites: ["kw-dependency-parsing", "kw-learner-language"],
    steps: [
      { order: 1, title: "工具准备", description: "安装并使用HanLP或LTP进行依存句法分析", duration: "10分钟" },
      { order: 2, title: "语料处理", description: "准备10篇不同水平的学习者作文", duration: "10分钟" },
      { order: 3, title: "句法特征提取", description: "计算平均句长、依存距离、从句比例等句法复杂度指标", duration: "20分钟", tips: ["使用L2SCA（二语句法复杂度分析器）作为参考", "按水平等级分组比较"] },
      { order: 4, title: "对比分析", description: "比较不同水平学习者的句法复杂度差异", duration: "10分钟" },
      { order: 5, title: "撰写分析笔记", description: "总结学习者句法发展规律和教学启示", duration: "5分钟" },
    ],
    deliverables: ["句法复杂度数据集", "依存分析结果", "分析笔记"],
    evaluationCriteria: ["句法分析正确", "特征提取合理", "分析有语言学意义"],
    relatedCourseIds: ["edunlp-008", "edunlp-014", "edunlp-004"],
    relatedKnowledgeIds: ["kw-dependency-parsing", "kw-learner-language"],
    relatedTaskIds: ["task-essay-grading", "task-feature"],
  },
  {
    id: "CP-LLM-004",
    title: "LLM幻觉检测与防范",
    description: "分析LLM在教育场景中的幻觉现象，设计和测试幻觉检测与防范策略。",
    objectives: ["理解LLM幻觉的成因和类型", "掌握幻觉检测的常用方法", "设计有效的幻觉防范Prompt"],
    level: 1,
    estimatedMinutes: 50,
    prerequisites: ["kw-llm-hallucination", "kw-llm-output-control"],
    steps: [
      { order: 1, title: "文献调研", description: "了解LLM幻觉的主要类型（事实错误、逻辑矛盾、编造信息等）", duration: "10分钟" },
      { order: 2, title: "构建测试集", description: "设计20个容易引发LLM幻觉的教育类问题", duration: "10分钟", tips: ["包括特定年代、具体数据、专业术语等", "设计一些不存在但有迷惑性的问题"] },
      { order: 3, title: "幻觉检测", description: "让LLM回答测试问题，人工或辅助工具标记幻觉", duration: "15分钟" },
      { order: 4, title: "防范策略测试", description: "设计多种防范Prompt（要求引用来源、不确定性表达、分步验证等），重新测试", duration: "10分钟" },
      { order: 5, title: "效果分析", description: "比较不同防范策略的幻觉率，总结最佳实践", duration: "5分钟" },
    ],
    deliverables: ["幻觉测试集", "防范策略Prompt库", "效果对比报告"],
    evaluationCriteria: ["测试集设计合理", "防范策略有效降低幻觉", "分析有洞见"],
    relatedCourseIds: ["llm-011", "llm-012"],
    relatedKnowledgeIds: ["kw-llm-hallucination", "kw-llm-output-control"],
    relatedTaskIds: ["task-llm-essay-feedback", "task-llm-error-detection"],
  },
  {
    id: "CP-LLM-005",
    title: "LLM模型对比与Benchmark",
    description: "使用标准化Benchmark评测不同LLM在教育NLP任务上的表现。",
    objectives: ["理解LLM评测的Benchmark方法", "学会设计评测实验", "能够客观比较模型性能"],
    level: 1,
    estimatedMinutes: 50,
    prerequisites: ["kw-llm-benchmark", "kw-llm-evaluation", "kw-llm-alignment"],
    steps: [
      { order: 1, title: "Benchmark调研", description: "了解主流LLM评测基准（C-Eval、CMMLU、SuperCLUE等）", duration: "10分钟" },
      { order: 2, title: "评测任务设计", description: "设计3个教育NLP评测子任务（文本分级、偏误检测、内容生成）", duration: "10分钟" },
      { order: 3, title: "多模型评测", description: "使用至少2个LLM对同一评测集进行测试", duration: "15分钟", tips: ["控制Prompt和参数一致", "记录API成本"] },
      { order: 4, title: "结果分析", description: "从准确率、一致性、成本等维度对比模型表现", duration: "10分钟" },
      { order: 5, title: "撰写评测报告", description: "整理评测结果，提出模型选择建议", duration: "5分钟" },
    ],
    deliverables: ["评测任务集", "模型对比报告", "选择建议"],
    evaluationCriteria: ["评测任务科学", "对比维度全面", "报告客观有数据支撑"],
    relatedCourseIds: ["llm-019", "llm-020"],
    relatedKnowledgeIds: ["kw-llm-benchmark", "kw-llm-evaluation", "kw-llm-alignment"],
    relatedTaskIds: ["task-llm-assessment"],
  },

  // ── Level 2: Phase Projects (Phase 2 & 3 gaps) ──

  {
    id: "P2-004",
    title: "可读性分析与阅读材料分级系统",
    description: "构建一个自动化的中文阅读材料可读性分析和分级系统，服务于教材编写和课堂教学。",
    objectives: ["掌握中文可读性分析的核心方法", "构建可复用的分级工具", "能够为教学提供量化的分级建议"],
    level: 2,
    estimatedMinutes: 420,
    prerequisites: ["kw-readability-analysis", "kw-learner-language", "kw-edunlp-workflow"],
    steps: [
      { order: 1, title: "指标调研", description: "研究中文可读性指标（字频、词频、句长、笔画数、语法复杂度等）", duration: "45分钟", tips: ["参考Readability Analyzer的方法", "注意中文特殊指标"] },
      { order: 2, title: "指标实现", description: "编程实现至少5个可读性指标的计算函数", duration: "90分钟" },
      { order: 3, title: "测试文本收集", description: "收集HSK1-6级阅读文本各5篇作为测试集", duration: "30分钟" },
      { order: 4, title: "指标计算与验证", description: "计算测试文本的各项指标，分析其与HSK等级的相关性", duration: "60分钟" },
      { order: 5, title: "分级模型构建", description: "基于指标权重构建分级评分模型", duration: "60分钟", tips: ["可使用PCA降维", "或构建简单的加权评分"] },
      { order: 6, title: "系统封装", description: "将分析功能封装为可复用的Python类或模块", duration: "45分钟" },
      { order: 7, title: "撰写研究报告", description: "整理方法、实验结果和教学应用建议", duration: "45分钟" },
    ],
    deliverables: ["可读性分析Python模块", "分级评测报告", "应用示例"],
    evaluationCriteria: ["指标体系科学完整", "分级准确率达标", "代码可复用"],
    relatedCourseIds: ["edunlp-009", "edunlp-011", "edunlp-014", "edunlp-015"],
    relatedKnowledgeIds: ["kw-readability-analysis", "kw-learner-language", "kw-edunlp-workflow"],
    relatedTaskIds: ["task-readability", "task-essay-grading", "task-exercise-gen"],
    phaseId: "cli",
  },
  {
    id: "P3-004",
    title: "基于RAG的国际中文教育知识问答系统",
    description: "构建一个完整的RAG知识问答系统，针对国际中文教育的语法、词汇和文化知识，实现可靠的问答服务。",
    objectives: ["掌握RAG系统的完整构建流程", "理解知识库构建的最佳实践", "能够优化RAG问答质量"],
    level: 2,
    estimatedMinutes: 480,
    prerequisites: ["kw-llm-rag", "kw-llm-vector-db", "kw-llm-embedding"],
    steps: [
      { order: 1, title: "知识库规划", description: "规划知识库范围和结构，覆盖HSK语法点、常见偏误、文化知识点等", duration: "60分钟", tips: ["每个知识点写成独立文档", "使用Markdown格式便于分块"] },
      { order: 2, title: "知识准备", description: "整理或编写50条以上的知识点文本", duration: "90分钟" },
      { order: 3, title: "向量数据库搭建", description: "搭建向量数据库（ChromaDB/Pinecone），将知识点向量化存储", duration: "60分钟", tips: ["注意分块大小（建议256-512 tokens）", "保留元数据标签"] },
      { order: 4, title: "RAG管线实现", description: "实现检索→重排序→Prompt组装→LLM生成完整管线", duration: "90分钟", tips: ["实现语义检索和关键词检索的混合", "设计多轮对话的上下文管理"] },
      { order: 5, title: "质量评估", description: "设计30个测试问题，评估回答的准确性和引用正确性", duration: "60分钟", tips: ["评估维度：准确性、完整性、引用正确性", "记录检索失败和幻觉案例"] },
      { order: 6, title: "优化迭代", description: "根据评估结果优化分块策略、检索参数和Prompt设计", duration: "60分钟" },
      { order: 7, title: "撰写系统报告", description: "记录系统架构、实现细节和评估结果", duration: "60分钟" },
    ],
    deliverables: ["RAG知识库", "问答系统代码", "质量评估报告"],
    evaluationCriteria: ["检索命中率达标", "回答准确率≥80%", "系统架构清晰"],
    relatedCourseIds: ["llm-008", "llm-009", "llm-013", "llm-015"],
    relatedKnowledgeIds: ["kw-llm-rag", "kw-llm-vector-db", "kw-llm-embedding", "kw-llm-agent", "kw-llm-tool-use"],
    relatedTaskIds: ["task-llm-qa-system", "task-llm-knowledge-base", "task-llm-classroom-assistant"],
    phaseId: "llm",
  },
  {
    id: "P3-005",
    title: "教学Agent设计与评测",
    description: "设计一个面向国际中文教育的智能教学Agent，能够执行多步教学任务并进行效果评估。",
    objectives: ["掌握Agent架构设计方法", "实现Agent的工具调用和记忆管理", "能够系统化评估Agent教学效果"],
    level: 2,
    estimatedMinutes: 480,
    prerequisites: ["kw-llm-agent", "kw-llm-tool-use"],
    steps: [
      { order: 1, title: "需求分析", description: "确定Agent的教学功能（如出题、批改、答疑、进度跟踪等）", duration: "45分钟" },
      { order: 2, title: "Agent架构设计", description: "设计Agent的系统架构：感知（输入处理）→规划（任务分解）→执行（工具调用）→反思（质量检查）", duration: "60分钟", tips: ["使用ReAct或Plan-and-Execute模式", "设计工具接口"] },
      { order: 3, title: "工具开发", description: "开发Agent可调用的教学工具（词典查询、语法检查、出题模板等）", duration: "90分钟" },
      { order: 4, title: "Agent实现", description: "实现完整的Agent循环，包括Prompt编排、工具调用、记忆管理", duration: "90分钟", tips: ["使用LangChain或手动编排", "实现短期记忆（对话历史）+ 长期记忆（学习者档案）"] },
      { order: 5, title: "教学效果评测", description: "设计评测方案，从准确性、教学适切性、交互体验等维度评估Agent", duration: "90分钟" },
      { order: 6, title: "优化迭代", description: "根据评测反馈优化Agent行为", duration: "60分钟" },
      { order: 7, title: "撰写设计报告", description: "记录Agent设计思路、实现方案和评测结果", duration: "45分钟" },
    ],
    deliverables: ["Agent系统代码", "工具模块", "教学效果评测报告"],
    evaluationCriteria: ["Agent可自主完成多步任务", "工具调用正确", "评测方法科学"],
    relatedCourseIds: ["llm-016", "llm-017", "llm-018"],
    relatedKnowledgeIds: ["kw-llm-agent", "kw-llm-tool-use", "kw-llm-evaluation", "kw-llm-benchmark"],
    relatedTaskIds: ["task-llm-agent-design", "task-llm-assessment", "task-llm-path-recommend"],
    phaseId: "llm",
  },
  {
    id: "P3-006",
    title: "LLM评测体系建设",
    description: "构建一套面向国际中文教育场景的LLM评测体系，覆盖安全性、对齐性和教学有效性。",
    objectives: ["掌握LLM评测的方法论体系", "构建教育领域评测数据集", "能够识别模型的潜在风险"],
    level: 2,
    estimatedMinutes: 440,
    prerequisites: ["kw-llm-evaluation", "kw-llm-benchmark", "kw-llm-alignment"],
    steps: [
      { order: 1, title: "评测维度设计", description: "确定教育场景LLM评测的核心维度（准确率、安全性、教学适切性、文化敏感性等）", duration: "60分钟", tips: ["参考Trustworthy AI框架", "结合教育领域的特殊要求"] },
      { order: 2, title: "评测集构建", description: "为每个维度构建不少于20个测试样本", duration: "120分钟" },
      { order: 3, title: "多模型评测", description: "使用评测集测试至少2个LLM，记录各维度得分", duration: "90分钟" },
      { order: 4, title: "对齐性分析", description: "分析LLM在安全性、公平性和价值观对齐方面的表现", duration: "60分钟", tips: ["关注偏见、有害内容、文化不敏感等", "记录对齐失败案例"] },
      { order: 5, title: "风险报告", description: "输出模型风险评估报告，标记Red Flag场景", duration: "60分钟" },
      { order: 6, title: "撰写评测报告", description: "整理完整的评测报告，提出模型选择和使用建议", duration: "50分钟" },
    ],
    deliverables: ["评测数据集", "多模型评测报告", "风险评估报告"],
    evaluationCriteria: ["评测维度科学全面", "数据集质量高", "风险识别准确"],
    relatedCourseIds: ["llm-019", "llm-020", "llm-021"],
    relatedKnowledgeIds: ["kw-llm-evaluation", "kw-llm-benchmark", "kw-llm-alignment", "kw-llm-hallucination"],
    relatedTaskIds: ["task-llm-assessment", "task-llm-essay-feedback", "task-llm-error-detection"],
    phaseId: "llm",
  },
  {
    id: "P3-007",
    title: "微调教育领域LLM",
    description: "使用教育领域数据对小型LLM进行微调，提升其在教育NLP任务上的表现。",
    objectives: ["理解模型微调的基本原理和流程", "掌握LoRA等高效微调方法", "能够评估微调效果"],
    level: 2,
    estimatedMinutes: 480,
    prerequisites: ["kw-llm-finetuning", "kw-llm-transformer", "kw-llm-inference"],
    steps: [
      { order: 1, title: "微调方法学习", description: "学习LoRA、QLoRA等参数高效微调方法的基本原理", duration: "60分钟" },
      { order: 2, title: "训练数据准备", description: "收集或构造教育领域的微调数据集（问答对、指令-输出对）", duration: "90分钟", tips: ["数据质量>数量", "包含正例和负例"] },
      { order: 3, title: "环境搭建", description: "搭建微调环境（如LLaMA-Factory、Unsloth等），准备GPU资源", duration: "60分钟" },
      { order: 4, title: "LoRA微调", description: "使用LoRA方法对基础模型进行微调", duration: "120分钟", tips: ["记录训练日志", "关注loss下降曲线"] },
      { order: 5, title: "效果评估", description: "使用测试集评估微调前后的性能差异", duration: "60分钟", tips: ["评估指标：准确率、BLEU、ROUGE等", "对比微调前后在同一任务的表现"] },
      { order: 6, title: "分析与总结", description: "分析微调效果，总结经验教训和可改进方向", duration: "45分钟" },
      { order: 7, title: "撰写实验报告", description: "记录完整的微调过程和评估结果", duration: "45分钟" },
    ],
    deliverables: ["微调脚本与配置", "训练数据集", "微调效果评估报告"],
    evaluationCriteria: ["微调流程完整", "评估方法科学", "效果提升合理"],
    relatedCourseIds: ["llm-010", "llm-014", "llm-022"],
    relatedKnowledgeIds: ["kw-llm-finetuning", "kw-llm-transformer", "kw-llm-inference", "kw-llm-attention"],
    relatedTaskIds: ["task-llm-hsk-gen", "task-llm-prompt-optimize"],
    phaseId: "llm",
  },
  {
    id: "P3-008",
    title: "AI辅助HSK出题系统",
    description: "构建一个使用LLM自动生成HSK标准试题的系统，包括词汇题、语法题和阅读理解题，并验证题目质量。",
    objectives: ["掌握LLM自动出题的核心方法", "实现多题型自动生成", "能够评估生成题目的质量"],
    level: 2,
    estimatedMinutes: 460,
    prerequisites: ["kw-llm-text-generation", "kw-llm-controlled-gen", "kw-llm-output-control"],
    steps: [
      { order: 1, title: "出题规范研究", description: "研究HSK考试题型规范和标准，确定要生成的题型", duration: "45分钟", tips: ["参考HSK真题格式", "注意题型多样性"] },
      { order: 2, title: "Prompt模板设计", description: "为每种题型设计专用Prompt模板（选词填空、造句、阅读理解等）", duration: "60分钟", tips: ["指定难度等级（HSK1-6）", "要求输出标准答案和解析"] },
      { order: 3, title: "受控生成实现", description: "实现词汇约束和语法结构控制，确保生成题目符合目标等级", duration: "90分钟" },
      { order: 4, title: "批量生成", description: "批量生成各题型各等级的题目，每个组合至少10道", duration: "60分钟" },
      { order: 5, title: "质量审核", description: "设计质量审核标准（答案正确性、内容适切性、难度匹配度等），对生成题目进行审核", duration: "90分钟", tips: ["可邀请教师参与审核", "记录审核通过率"] },
      { order: 6, title: "优化迭代", description: "根据审核结果优化Prompt模板和约束策略", duration: "60分钟" },
      { order: 7, title: "撰写系统报告", description: "整理系统设计、生成结果和审核数据", duration: "45分钟" },
    ],
    deliverables: ["出题Prompt模板库", "生成题目集", "质量审核报告"],
    evaluationCriteria: ["题型覆盖全面", "题目审核通过率≥70%", "等级控制准确"],
    relatedCourseIds: ["llm-015", "llm-016", "llm-023"],
    relatedKnowledgeIds: ["kw-llm-text-generation", "kw-llm-controlled-gen", "kw-llm-output-control", "kw-llm-context-window"],
    relatedTaskIds: ["task-llm-question-gen", "task-llm-reading-gen", "task-llm-hsk-gen"],
    phaseId: "llm",
  },
]
